### ISSUE TITLE
Why do train episodes contain eval goals?

### ISSUE THREAD

**Issue by linamez** [orybkin/lexa#1]
When training a model with `lexa_cosine` on `dmc_walker_walk` and visualising the episodes contained in `{logdir}\train_eps`, I noticed that these episodes had for `image_goal` an image from the eval set of goals. Why ? And how to visualise the actual train goals ?

**Comment by orybkin** [comment]
Hi Lina,

Can you share 4-5 images you are seeing that are the same as the eval set? Would be great to also share the state vectors for these images.

**Comment by linamez** [comment]
Here are 3 examples:
1. ![image](https://user-images.githubusercontent.com/35572460/146219267-e50b2b46-94ff-4f4b-b136-06a6e59aaa9e.png)
state: [-0.5 ,  0.  ,  0.  ,  0.  , -1.57, -0.8 ,  1.57, -1.57,  0.  ]

2. ![image](https://user-images.githubusercontent.com/35572460/146219528-891f8c7f-b775-4be6-ad61-c4a84372f19d.png)
state: [-1. ,  0. , -3. ,  0.6, -1. , -0.3,  0.9, -0.5,  0.3]

3. ![image](https://user-images.githubusercontent.com/35572460/146220374-084ca908-bc27-497b-aeb6-b27119911763.png)
state: [-0.2 ,  0.  ,  0.  ,  0.7 , -1.34,  0.5 ,  1.5 , -0.6 ,  0.1 ]

To be clear, I visualized train episodes at random in `{logdir}\train_eps`, and all of the image_goal I saw were from the eval set.

Thanks for helping :)

**Comment by orybkin** [comment]
Ah I see what's happening. The image_goal in the training dataset is indeed from the eval set. However, it is not used by the agent. Ideally, we would clean this up and instead save the image the agent used, we just didn't get to it.

I am afraid the actual goal used by the agent is not saved in the replay buffer since it is not necessary. The policy optimization only uses imagined rollouts so we never need the goals on the real data. If you wanted to visualize the actual goals, you could try saving them. This would unfortunately require understanding the dreamer code we use, but if you start with this function: https://github.com/orybkin/lexa/blob/bf112056e0d7f9e044dce053ddc757600cd99d2e/lexa/tools.py#L212 you could probably figure it out.

**Comment by linamez** [comment]
Ok yeah, this makes sense.

I'll have a look at it, thanks a lot for your help!
